SELECT TOP (1000) [order_id]
      ,[order_item_id]
      ,[product_id]
      ,[seller_id]
      ,[shipping_limit_date]
      ,[price]
      ,[freight_value]
  FROM [Archive].[dbo].[Order_items]
